FROM centos:8

ENV GOVERSION 1.14.6

RUN yum module enable -y idm:DL1 && \
    yum install -y rpm-build ruby wget gcc git softhsm softhsm-devel && \
    yum clean all

RUN wget -q https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GOVERSION}.linux-amd64.tar.gz && \
    rm -f go${GOVERSION}.linux-amd64.tar.gz

WORKDIR /build/source

VOLUME /go
VOLUME /build/artifacts

ENV RUBYLIB /packager/lib
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
ENV GOPATH /go
ENV GO111MODULE on

COPY lib /packager/lib/
COPY bin /packager/bin/

CMD /packager/bin/packager.rb
