FROM centos:6

ENV GOVERSION 1.14

RUN rpm -ivh http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm && \
    yum install -y rpm-build ruby wget gcc git && \
    yum clean all

RUN wget -q https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GOVERSION}.linux-amd64.tar.gz && \
    rm -f go${GOVERSION}.linux-amd64.tar.gz

WORKDIR /build/source

VOLUME /go
VOLUME /build/artifacts

ENV RUBYLIB /packager/lib
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
ENV GOPATH /go
ENV GO111MODULE on

COPY lib /packager/lib/
COPY bin /packager/bin/

CMD /packager/bin/packager.rb
