FROM centos:8

RUN yum install -y rpm-build ruby wget gcc git && \
    yum clean all

# bit weird, this clearly exist but yum aint finding it in current metadata, probably a fix soon
RUN yum install -y http://mirror.centos.org/centos-8/8.0.1905/AppStream/x86_64/os/Packages/softhsm-2.4.0-2.module_el8.0.0+79+bbd20d7b.x86_64.rpm

RUN wget -q https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.13.7.linux-amd64.tar.gz && \
    rm -f go1.13.7.linux-amd64.tar.gz

WORKDIR /build/source

VOLUME /go
VOLUME /build/artifacts

ENV RUBYLIB /packager/lib
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
ENV GOPATH /go
ENV GO111MODULE on

COPY lib /packager/lib/
COPY bin /packager/bin/

CMD /packager/bin/packager.rb
